### PR TITLE
Bump nomad to 4.2

### PR DESCRIPTION
**Pull request by SobhanMP**
removes the deprecated options. should be merged after https://github.com/JuliaPackaging/Yggdrasil/pull/5182 and https://github.com/bbopt/NOMAD.jl/pull/59 are merged. Alternatively, merge this and close #59 w/o squashing. The binaries can be found https://github.com/SobhanMP/NOMAD_jll.jl

### CODE REVIEW

**Comment by SobhanMP** [comment]
the CI is going to fail because NOMAD_jll 4.2 is not available in the registery.

**Comment by amontoison** [comment]
@SobhanMP
The main developer of NOMAD was not working the last three weeks (summer holidays) but it fixed the issue with MinGW compilation today!
It will test if everything works fine tomorrow. We should be able to update the `build_tarballs.jl` after that.

**Comment by SobhanMP** [comment]
cool

**Comment by amontoison** [comment]
@SobhanMP I can't merge the PR due to conflits.
@solomonl Can you review the PR ?

**Comment by SobhanMP** [comment]
image
what branch do you want to merge it to?

**Comment by amontoison** [comment]
Capture d’écran du 2022-08-19 00-39-05
I want to merge it to `master` :thinking:

**Comment by SobhanMP** [comment]
❯ git pull upstream master
From https://github.com/bbopt/NOMAD.jl
 * branch            master     -> FETCH_HEAD
Already up to date.


maybe use the command line instructions?

**Comment by amontoison** [comment]
> ❯ git pull upstream master From https://github.com/bbopt/NOMAD.jl
> 
> * branch            master     -> FETCH_HEAD
>   Already up to date.
> 
> maybe use the command line instructions?

Did you try `git rebase upstream master` ?
The other `Squash and merge` is available for me but I don't understand why I can't do `Rebase and merge`.

**Review by salomonl — APPROVED** [review]

**Comment by amontoison** [comment]
Thanks @SobhanMP !
I did a squash + merge.

**Pull request merged**
