### PR TITLE
Allows custom installation

### PR DESCRIPTION
**Pull request by amontoison**
@salomonl 

I use the same trick with `qr_mumps`.
It could be relevant for you when you want to add features to the C code / interface of NOMAD.
What do you think about it ?

### CODE REVIEW

**Comment by salomonl** [comment]
It seems as a good idea. But the CInterfarce library is not located at the same folder as for the other. Have you tested it ?

**Comment by amontoison** [comment]
No, I didn't test it. It's for that reason that I tagged you.
I have an old version of NOMAD that compiles the libraries `libnomadAlgos.so`, `libnomadEval.so`, `libnomadInterface.so`, `libnomadUtils.so` and `libsgtelib.so` in the same folder `.../NOMAD/build/lib`.

**Comment by salomonl** [comment]
Sorry for the delay. I finally have found how to test the pull request locally.
You do not need to indicate the path for `libnomadAlgos`, `libnomadEval`, `libnomadUtils`, `libsgtelib` library paths (at least on my machine). They are linked to the `libnomadCInterface`.

**Comment by salomonl** [comment]
Maybe it could be a good idea to mention it in the documentation ?

**Pull request merged**
